# 协程
---
基于Python 3.4 以上

## 用作协程生成器的基本行为

## 预激活协程

* 通过自定义的 装饰器 激活
* yield from 自带预激活功能

## 终止协程和异常处理

协程中未处理的异常会向上冒泡, 传给 next 函数 或者 send 方法的调用方(即触发协程的对象).

客户代码可以在生成器对象上调用两个方法, 显示的把异常发给协程

`generator.throw(exc_type[, exc_value[, trackback]])`:
致使生成器在暂停的 yield 表达式处抛出指定异常. 如果生成器处理了抛出的异常, 代码会向前执行到下一个 yield 表达式, 而产出的值会成为调用generator.throw 方法得到的返回值. 如果生成器没有处理抛出的异常, 异常会向上冒泡, 直到调用方的上下文中.(即代码中处理的异常, 协程会继续运行, 没有处理会向上抛出异常, 中断协程)

`generator.close()`: 致使生成器在暂停的 yield 表达式处抛出 GeneratorExit 异常. 如果生成器没有处理这个异常, 或者抛出了 StopIteration 异常(通常是指运行到结尾), 调用方不会报错. 如果收到 GeneratorExit 异常, 生成器一定不能产出值, 否则解释器会抛出 RuntimeError 异常. 生成器抛出的其他的异常会向上冒泡, 传给调用方.

```py
class DemoException(Exception):
    """yanshi yichang """
    pass

def demo_exc_handling():
    print("-> coroutine started")
    while True:
        try:
            x = yield
        except DemoException:
            print("*** DemoException handled. Continuing...")
        else:
            print('-> corotine received: {!r}'.format(x))
    raise RuntimeError('This line should never run.')
~                                                       
```

```
In [22]: exc_coro = demo_exc_handling()

In [23]: next(exc_coro)
-> coroutine started

In [24]: exc_coro.send(11)
-> corotine received: 11

In [25]: exc_coro.send(22)
-> corotine received: 22

In [26]: exc_coro.close()

In [27]: getgeneratorstate(exc_coro)
Out[27]: 'GEN_CLOSED'

In [28]: 

```

把 DemoException 异常传入 demo_exc_handling 不会导致协程终止
```
In [30]: exc_coro = demo_exc_handling()

In [31]: next(exc_coro)
-> coroutine started

In [32]: exc_coro.send(11)
-> corotine received: 11

In [33]: exc_coro.send(22)
-> corotine received: 22

In [34]: exc_coro.throw(DemoException)
*** DemoException handled. Continuing...

In [35]: getgeneratorstate(exc_coro)
Out[35]: 'GEN_SUSPENDED'

```

传入无法处理的异常 会 终止
```
>>> exc_coro = demo_exc_handling()
>>> next(exc_coro)
-> coroutine started
>>> exc_coro.send(11)
-> coroutine received: 11
>>> exc_coro.throw(ZeroDivisionError)
Traceback (most recent call last):
...
ZeroDivisionError
>>> getgeneratorstate(exc_coro)
'GEN_CLOSED'
```


## 让协程返回值


```py
from collections import namedtuple
Result = namedtuple('Result', 'count average')

def averager():
    total = 0.0
    count = 0
    average = None
    while True:
        term = yield
            if term is None:
                break
        total += term
        count += 1
        average = total/count
    return Result(count, average)
```
发送 None  会终止循环, 导致协程结束, 返回结果. 生成器对象会抛出 StopIteration 异常. 异常对象的 value属性保存值返回的值.

注意, return 表达式的值会偷偷的传给调用方, 复制给StopIteration 异常的一个属性. 这样做有点不合常理，但是能保留生成器对象的常规
行为——耗尽时抛出 StopIteration 异常

```
>>> coro_avg = averager()
>>> next(coro_avg)
>>> coro_avg.send(10)
>>> coro_avg.send(30)
>>> coro_avg.send(6.5)
>>> try:
...     coro_avg.send(None)
... except StopIteration as exc:
...     result = exc.value
...
>>> result
Result(count=3, average=15.5)
```


yield from 结构会在内部自动捕获
StopIteration 异常。这种处理方式与 for 循环处理 StopIteration
异常的方式一样：循环机制使用用户易于理解的方式处理异常。对
yield from 结构来说，解释器不仅会捕获 StopIteration 异常，还
会把 value 属性的值变成 yield from 表达式的值


## yield from
